# ActiveJob::Notificare configuration
#
# Generated by: rails generate active_job:notificare:install
#
# Notificare is a projection layer over ActiveJob::Continuation. Including
# `ActiveJob::Notificare` in a job pulls in Continuation, the step DSL, and the
# notification primitives.
#
# Allow access to the engine admin UI in all environments for this demo.
ActiveJob::Notificare.authenticate_with = -> { true }

# Resolve the current recipient for the engine's notifications controller.
ActiveJob::Notificare.current_recipient_proc = -> { current_user }
